### ISSUE TITLE
Linux build instructions don't work as written (on Ubuntu 18.04)

### ISSUE THREAD

**Issue by PAndaContron** [msrst/interactive-8051-disassembler#2]
The readme says to install `libboost-dev`, however this doesn't install all of the components of boost used by this program. Installing `libboost-all-dev` works, but this definitely installs more parts of boost than this program actually needs, so it might be worth figuring out which packages specifically are required.

Also, the Linux build instructions are missing the command `cmake --build .` after `cmake ..`, which actually builds the executable.

**Comment by msrst** [comment]
Hi,
thank you for your feedback. I updated + tested the build instructions on Ubuntu 20.04.
Feel free to reach out if there are any other issues or if you need Ubuntu 18.04 instructions (or you have tips for other distros).
